theme: minima
title: Uh Hello, Welcome to my Blog
author: SailrAyanami on Github
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
This is where an awesome description of myself should go, but I dont seem to have the vocabulary to describe my current project.
# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
